<?php
$method     = $this->getMethod();
$qrCodeUrl  = $this->getPixQrCodeUrl();
$qrCode     = $this->getPixQrCode();
$expiration = $this->getExpirationDate();
?>

<span><strong><?php echo __($this->getTitle()) ?></strong></span>

<?php if ($method == "iopay_pix"): ?>
    <br>
    <span>Pagar até: <?php echo $expiration; ?></span>
    <hr />
    <div style="">
        <img width="150" style="margin-bottom: 10px" src="<?= $qrCodeUrl; ?>" />
        <span style="word-wrap: break-word;"><?= $qrCode; ?></span>
    </div>
<?php endif; ?>

